// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about";
  };
  "./home/index.tsx": {
    id: "home/index";
    page: "/";
  };
  "./about/index.tsx": {
    id: "about/index";
    page: "/about";
  };
};